# Site settings
title: Coding, Tech and All That Other Fun Stuff
header-img: img/home-bg.png
email: cynsand@gmail.com
copyright_name: cynthiasandoval
description: > # this means to ignore newlines until "baseurl:"
  Follow me on my journey to becoming a coding ninja!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  cynthiasandoval
learn_profile: cynthiasandoval
email_username: cynsand@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
